# Generated by Django 5.2.5 on 2025-08-20 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_pedido', models.DateField()),
                ('fecha_llegada_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('obligatorio', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.contenedor')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.contenedor')),
            ],
        ),
    ]
